[package]
name = "vpn"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { version = "0.2.153", features = ["std"], default-features = false }
ipnet = { version = "2.9.0", features = ["std"], default-features = false }
